apiVersion: v1
items:
- apiVersion: neuvector.com/v1
  kind: NvSecurityRule
  metadata:
    name: nv.{{ .Release.Namespace }}.{{ .Release.Name }}
  spec:
    dlp:
      settings: []
      status: true
    egress:
    - action: allow
      applications:
      - HTTP
      name: nv.{{ .Release.Namespace }}.{{ .Release.Name }}-egress-0
      ports: any
      priority: 0
      selector:
        comment: ""
        criteria:
        - key: suse.com/appName
          op: =
          value: pong
        - key: domain
          op: =
          value: pong-{{ .Values.suffix }}
        name: pong-prd
        original_name: ""
    file: []
    ingress:
    - action: allow
      applications:
      - HTTP
      name: nv.{{ .Release.Namespace }}.{{ .Release.Name }}-ingress-0
      ports: tcp/80
      priority: 0
      selector:
        comment: ""
        criteria: []
        name: nodes
        original_name: ""
    process:
    - action: allow
      allow_update: false
      name: hello-world
      path: /opt/hello-world/hello-world
    - action: allow
      allow_update: false
      name: pause
      path: /pause
    - action: allow
      allow_update: false
      name: curl
      path: /usr/bin/curl
    - action: allow
      allow_update: false
      name: busybox
      path: /bin/busybox
    - action: allow
      allow_update: false
      name: sh
      path: /bin/busybox
    process_profile:
      baseline: zero-drift
    target:
      policymode: Protect
      selector:
        comment: ""
        criteria:
        - key: service
          op: =
          value: {{ include "nv-ping.fullname" . }}.{{ .Release.Namespace }}
        - key: domain
          op: =
          value: {{ .Release.Namespace }}
        name: nv.{{ include "nv-ping.fullname" . }}.{{ .Release.Namespace }}
        original_name: ""
    waf:
      settings: []
      status: true
kind: List
metadata: null